### ISSUE TITLE
Drop down list for country 

### ISSUE THREAD

**Issue by darkneon2002** [DanielMartinus/Passcoder#10]
A drop  down list for country selection would be more efficient. This will avoid countries duplicates in English and the foreign language.

**Comment by DanielMartinus** [comment]
Couple of reasons i didn't choose for a dropdown lists.
The list of countries is so large that it would not be efficient to use a dropdown list. I could use a fragment (other screen) to select the country with a fast selecting mechanism as alphabetical slider or search. But then you also have to select your city.

The reason i choose for filling in the country and city yourself is because it will be geocoded to latitude and longitude. The differences that people give up, for example: USA, US, United States, United States of America USoA, U.S., U.S.A. Doesn't really matter since it will be geocded and as long the geocoder api will recognize it its good to go.
